# Generated by Django 3.2.12 on 2022-05-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comments', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('experience', models.CharField(choices=[('BEG', 'have not been on a horse'), ('INT', 'have been on a horse but feel unsure'), ('ADV', 'can ride a horse when it walks'), ('EXP', 'can ride a horse in all speeds'), ('PRO', 'Professional')], max_length=3)),
                ('gallop', models.CharField(choices=[('EVE', 'Everyone in group wants to Gallop'), ('FEW', 'Few in group want to Gallop'), ('NOB', 'Nobody in group wants to Gallop'), ('WAL', 'We only want to walk on the horses')], default='Nobody', max_length=30)),
                ('snacks', models.CharField(choices=[('0KR', 'No Snacks'), ('50KR', 'Coffee-saft-buns'), ('100KR', 'Coffes-aft-buns-princess-cake')], default='None', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
