# Generated by Django 4.0.4 on 2022-05-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_individual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='individual',
        ),
    ]
